
export const ADD_PROJECT = "ADD_PROJECT";
export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const PROJECT_ERROR = "PROJECT_ERROR";
export const SET_ALERT = "SET_ALERT";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_DETAIL = "GET_DETAIL";
export const FILTERS = "FILTERS";
export const ORDER_CATEGORIES = "ORDER_CATEGORIES";
export const FILTER_CLEAR = "FILTER_CLEAR";

export const GET_PROJECTS_BY_NAME = "GET_PROJECTS_BY_NAME";
export const GET_USER_BY_ID = "GET_USER_BY_ID";

