import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button } from "@nextui-org/react";

export default function Home() {
  return (
    <div className="indigo-light text-foreground bg-background">
      <Head>
        <title>ProjUnity</title>
        <meta name="description" content="Generated by create next app" />
      {/*   <link rel="icon" href="/favicon.ico" /> */}
        <link  rel="icon" type="image/png" href="/favicon.png" />
      </Head>

      <main>
        <Button color="primary" variant="solid">
          Solid
        </Button>
        <Button color="secondary" variant="ghost">
          Ghost
        </Button>
        es el main
      </main>

      <footer>es un footer</footer>
    </div>
  );
}
