import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button } from "@nextui-org/react";
import LayoutUser from "../components/layoutUser";

export default function Home() {
  return (
    <LayoutUser>
      <Head>
        <title>ProjUnity</title>
        <meta name="description" content="Generated by create next app" />
        {/*   <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>

      <main></main>
    </LayoutUser>
  );
}
